---
output:
  html_document:
    df_print: paged
    keep_md: yes
  word_document: default
  pdf_document:
    fig_caption: yes
    includes:
    keep_tex: yes
    number_sections: no
title: "WHAM figures and tables"
header-includes:
  - \usepackage{longtable}
  - \usepackage{booktabs}
  - \usepackage{caption,graphics}
  - \usepackage{makecell}
  - \usepackage{lscape}
  - \renewcommand\figurename{Fig.}
  - \captionsetup{labelsep=period, singlelinecheck=false}
  - \newcommand{\changesize}[1]{\fontsize{#1pt}{#1pt}\selectfont}
  - \renewcommand{\arraystretch}{1.5}
  - \renewcommand\theadfont{}
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy=FALSE, tidy.opts=list(width.cutoff=60), warning = FALSE, message = FALSE, fig.align = "center")
options(knitr.kable.NA = "--")
library(knitr)
library(tidyverse)
library(pander)
library(kableExtra)
library(png)
library(tinytex)
```
# {.tabset}

## Figures {.tabset}

### Input

### Diagnostics

### Results

## Tables {.tabset}

### Parameter estimates

```{r par-table, echo=FALSE, message=FALSE, warnings=FALSE, error = FALSE, results='asis'}
type = "latex"
if(knitr::is_latex_output()) type = "latex"
if(knitr::is_html_output()) type = "html"
out = readRDS("parameter_estimates_table.RDS")
out = round(out, 3)
out <- out %>% kable(format = type, booktabs = T, escape=F, longtable = T, row.names = T,label = "par-table",
    caption="Parameter estimates, standard errors, and confidence intervals. Rounded to 3 decimal places.") %>%
    kable_styling(latex_options=c("basic", "repeat_header")) %>% landscape()
cat(knitr::knit_print(out))

input <- readRDS("fit_input.RDS")
dat <- input$data
  stock.names.tab <- gsub("_", " ", mod$input$stock_names, fixed = TRUE)
  region.names.tab <- gsub("_", " ", mod$input$region_names, fixed = TRUE)
  index.names.tab <- gsub("_", " ", mod$input$index_names, fixed = TRUE)
  fleet.names.tab <- gsub("_", " ", mod$input$fleet_names, fixed = TRUE)
```

### Abundance at age

```{r echo=FALSE, message=FALSE, warnings=FALSE, error = FALSE, results='asis'}
for(s in 1:dat$n_stocks) for(r in 1:dat$n_regions){
  out = readRDS(paste0(input$stock_names[s], "_", input$region_names[r], "_NAA_table.RDS"))
  out = round(out, 0)
  out <- out %>% kable(format = type, booktabs = T, escape=F, longtable = T, row.names = T, label = paste0("S-",s, "-R-",r, "-NAA-table"), 
      caption=paste0("Abundance at age (1000s) for ", stock.names.tab[s], " in ", region.names.tab[r],".")) %>%
      kable_styling(latex_options=c("basic", "repeat_header")) #%>%
  cat(knitr::knit_print(out))
}
```

### Fishing mortality at age by region

```{r echo=FALSE, message=FALSE, warnings=FALSE, error = FALSE, results='asis'}
for(r in 1:dat$n_regions){
  out = readRDS(paste0(input$region_names[r], "_FAA_tot_table.RDS"))
  out = round(out, 3)
  out <- out %>% kable(format = type, booktabs = T, escape=F, longtable = T, row.names = T, label = paste0("R-", r, "-FAA-tot-table"),
      caption=paste0("Total fishing mortality at age in ", region.names.tab[r], ".")) %>%
      kable_styling(latex_options=c("basic", "repeat_header")) #%>%
  cat(knitr::knit_print(out))
}
```

### Fishing mortality at age by fleet

```{r echo=FALSE, message=FALSE, warnings=FALSE, error = FALSE, results='asis'}
for(r in 1:dat$n_fleets){
  out = readRDS(paste0(input$fleet_names[r], "_FAA_table.RDS"))
  out = round(out, 3)
  out <- out %>% kable(format = type, booktabs = T, escape=F, longtable = T, row.names = T, label = paste0("R-", r, "-FAA-tot-table"),
      caption=paste0("Total fishing mortality at age in ", fleet.names.tab[r], ".")) %>%
      kable_styling(latex_options=c("basic", "repeat_header")) #%>%
  cat(knitr::knit_print(out))
}
```
