<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ex 2: Recruitment linked to an environmental covariate (Cold Pool Index) • wham</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Ex 2: Recruitment linked to an environmental covariate (Cold Pool Index)">
<meta property="og:description" content="wham">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">wham</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-book"></span>
     
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/index.html">Overview</a>
    </li>
    <li>
      <a href="../articles/ex1_SNEMA_yellowtail_flounder.html">Ex 1: The basics</a>
    </li>
    <li>
      <a href="../articles/ex2_CPI_recruitment_SNEMA_yellowtail.html">Ex 2: Recruitment linked to an environmental covariate (Cold Pool Index)</a>
    </li>
    <li>
      <a href="../articles/ex3_projections.html">Ex 3: Projecting / forecasting random effects</a>
    </li>
    <li>
      <a href="../articles/ex4_selectivity.html">Ex 4: Selectivity with time- and age-varying random effects</a>
    </li>
    <li>
      <a href="../articles/ex5_GSI_M.html">Ex 5: Time-varying natural mortality linked to the Gulf Stream Index</a>
    </li>
    <li>
      <a href="../articles/ex6_NAA.html">Ex 6: Numbers-at-age / survival deviations as random effects</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-file-code-o"></span>
     
    Functions
  </a>
</li>
<li>
  <a href="https://github.com/timjmiller/wham/">
    <span class="fa fa-github fa-lg"></span>
     
    Source code
  </a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/timjmiller/wham/issues/">
    <span class="fa fa-question-circle-o"></span>
     
    Issues
  </a>
</li>
<li>
  <a href="https://www.fisheries.noaa.gov/contact/timothy-miller-phd">
    <span class="far fa far fa-paper-plane fa-lg"></span>
     
    Contact
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Ex 2: Recruitment linked to an environmental covariate (Cold Pool Index)</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/timjmiller/wham/blob/master/vignettes/ex2_CPI_recruitment_SNEMA_yellowtail.Rmd"><code>vignettes/ex2_CPI_recruitment_SNEMA_yellowtail.Rmd</code></a></small>
      <div class="hidden name"><code>ex2_CPI_recruitment_SNEMA_yellowtail.Rmd</code></div>

    </div>

    
    
<p>In this vignette we walk through an example using the <code>wham</code> (WHAM = Woods Hole Assessment Model) package to run a state-space age-structured stock assessment model. WHAM is a generalization of code written for <a href="https://doi.org/10.1139/cjfas-2015-0339">Miller et al. (2016)</a> and <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/fog.12236">Xu et al. (2018)</a>, and in this example we apply WHAM to the same stock, Southern New England / Mid-Atlantic Yellowtail Flounder.</p>
<p>This is the 2nd <code>wham</code> example, which builds off model <code>m4</code> from example 1 (full state-space model, numbers at all ages are random effects, logistic normal age-compositions). We assume you already have <code>wham</code> installed. If not, see the <a href="https://timjmiller.github.io/wham/">Introduction</a>. The simpler 1st example, without environmental effects, is available as a <a href="https://github.com/timjmiller/wham/blob/master/inst/example_scripts/ex1_SNEMA_yellowtail_flounder.R">R script</a> and <a href="https://timjmiller.github.io/wham/articles/ex1_SNEMA_yellowtail_flounder.html">vignette</a>.</p>
<p>In example 2, we demonstrate how to specify and run WHAM with varying</p>
<ul>
<li><p>recruitment models (random, Bev-Holt, Ricker)</p></li>
<li><p>environmental covariate (Cold Pool Index, CPI) process models (random walk, AR1), and</p></li>
<li><p>how the CPI affects recruitment (controlling or limiting)</p></li>
</ul>
<p>As in <a href="https://timjmiller.github.io/wham/articles/ex1_SNEMA_yellowtail_flounder.html">example 1</a>, we check that each model converges (<code><a href="../reference/check_convergence.html">check_convergence()</a></code>), plot diagnostics, results, and reference points (<code><a href="../reference/plot_wham_output.html">plot_wham_output()</a></code>), and compare models using AIC and Mohn’s rho (<code><a href="../reference/compare_wham_models.html">compare_wham_models()</a></code>).</p>
<div id="prepare-wham" class="section level2">
<h2 class="hasAnchor">
<a href="#prepare-wham" class="anchor"></a>1. Prepare <code>wham</code>
</h2>
<p>Open R and load the <code>wham</code> package:</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">wham</span>)</pre></body></html></div>
<p>For a clean, runnable <code>.R</code> script, look at <code>ex2_CPI_recruitment_SNEMA_yellowtail.R</code> in the <code>example_scripts</code> folder of the <code>wham</code> package install:</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="no">wham.dir</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/find.package.html">find.package</a></span>(<span class="st">"wham"</span>)
<span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="no">wham.dir</span>, <span class="st">"example_scripts"</span>)</pre></body></html></div>
<p>You can run this entire example script with:</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="no">write.dir</span> <span class="kw">&lt;-</span> <span class="st">"choose/where/to/save/output"</span> <span class="co"># otherwise will be saved in working directory</span>
<span class="fu"><a href="https://rdrr.io/r/base/source.html">source</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="no">wham.dir</span>, <span class="st">"example_scripts"</span>, <span class="st">"ex2_CPI_recruitment_SNEMA_yellowtail.R"</span>))</pre></body></html></div>
<p>Let’s create a directory for this analysis:</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="co"># choose a location to save output, otherwise will be saved in working directory</span>
<span class="no">write.dir</span> <span class="kw">&lt;-</span> <span class="st">"choose/where/to/save/output"</span>
<span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span>(<span class="no">write.dir</span>)
<span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span>(<span class="no">write.dir</span>)</pre></body></html></div>
<p>WHAM was built by modifying the ADMB-based ASAP model code <a href="http://sedarweb.org/docs/wsupp/S12RD06%20ASAPdoc.pdf">(Legault and Restrepo 1999)</a>, and is designed to take an ASAP3 .dat file as input. We generally assume in <code>wham</code> that you have an existing ASAP3 .dat file. If you are not familiar with ASAP3 input files, see the <a href="https://www.nefsc.noaa.gov/nft/ASAP.html">ASAP documentation</a>. For this vignette, an example ASAP3 input file is provided, <code>ex2_SNEMAYT.dat</code>. We will also need a data file with an environmental covariate, the Cold Pool Index, <code>CPI.csv</code>.</p>
<p>Copy <code>ex2_SNEMAYT.dat</code> and <code>CPI.csv</code> to our analysis directory:</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="no">wham.dir</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/find.package.html">find.package</a></span>(<span class="st">"wham"</span>)
<span class="fu"><a href="https://rdrr.io/r/base/files.html">file.copy</a></span>(<span class="kw">from</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="no">wham.dir</span>,<span class="st">"extdata"</span>,<span class="st">"ex2_SNEMAYT.dat"</span>), <span class="kw">to</span><span class="kw">=</span><span class="no">write.dir</span>, <span class="kw">overwrite</span><span class="kw">=</span><span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/base/files.html">file.copy</a></span>(<span class="kw">from</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="no">wham.dir</span>,<span class="st">"extdata"</span>,<span class="st">"CPI.csv"</span>), <span class="kw">to</span><span class="kw">=</span><span class="no">write.dir</span>, <span class="kw">overwrite</span><span class="kw">=</span><span class="fl">FALSE</span>)</pre></body></html></div>
<p>Confirm you are in the correct directory and it has the required data files:</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span>()
<span class="co">#&gt;  [1] "CPI.csv"                "ex1_SNEMAYT.dat"        "ex1_test_results.rds"  </span>
<span class="co">#&gt;  [4] "ex2_SNEMAYT.dat"        "ex2_test_results.rds"   "ex4_test_results.rds"  </span>
<span class="co">#&gt;  [7] "ex5_summerflounder.dat" "ex5_test_results.rds"   "ex6_test_results.rds"  </span>
<span class="co">#&gt; [10] "GSI.csv"</span></pre></body></html></div>
<p>Read the ASAP3 .dat file into R and convert to input list for wham:</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="no">asap3</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/read_asap3_dat.html">read_asap3_dat</a></span>(<span class="st">"ex2_SNEMAYT.dat"</span>)</pre></body></html></div>
<p>Load the environmental covariate (Cold Pool Index, CPI) data into R:</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="no">env.dat</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span>(<span class="st">"CPI.csv"</span>, <span class="kw">header</span><span class="kw">=</span><span class="no">T</span>)</pre></body></html></div>
<p>We generally abbreviate ‘environmental covariate’ as <code>ecov</code> in the code. In this example, the <code>ecov</code> data file has columns for observations (<code>CPI</code>), standard error (<code>CPI_sigma</code>), and year (<code>Year</code>). Observations and year are always required. Standard error can be treated as fixed/data with yearly values (as here) or one overall value shared among years. It can also be estimated as a parameter(s), likewise either as yearly values or one overall value.</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">env.dat</span>)
<span class="co">#&gt;   Year     CPI CPI_sigma</span>
<span class="co">#&gt; 1 1973  0.5988    0.2838</span>
<span class="co">#&gt; 2 1974 -0.1760    0.2465</span>
<span class="co">#&gt; 3 1975 -1.1887    0.2539</span>
<span class="co">#&gt; 4 1976 -0.7938    0.2634</span>
<span class="co">#&gt; 5 1977 -0.6771    0.1576</span>
<span class="co">#&gt; 6 1978 -1.5195    0.2045</span></pre></body></html></div>
</div>
<div id="specify-models" class="section level2">
<h2 class="hasAnchor">
<a href="#specify-models" class="anchor"></a>2. Specify models</h2>
<p>Now we specify how the 7 models treat recruitment, the CPI process, and how the CPI affects recruitment:</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="no">df.mods</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="kw">Recruitment</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>,<span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">3</span>,<span class="fl">3</span>,<span class="fl">3</span>,<span class="fl">4</span>),
                      <span class="kw">ecov_process</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="st">"rw"</span>,<span class="fl">4</span>),<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="st">"ar1"</span>,<span class="fl">3</span>)),
                      <span class="kw">ecov_how</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">2</span>,<span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">1</span>), <span class="kw">stringsAsFactors</span><span class="kw">=</span><span class="fl">FALSE</span>)
<span class="no">n.mods</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(<span class="no">df.mods</span>)[<span class="fl">1</span>]
<span class="no">df.mods</span>$<span class="no">Model</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="st">"m"</span>,<span class="fl">1</span>:<span class="no">n.mods</span>)
<span class="no">df.mods</span> <span class="kw">&lt;-</span> <span class="kw pkg">dplyr</span><span class="kw ns">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(<span class="no">df.mods</span>, <span class="no">Model</span>, <span class="kw pkg">tidyselect</span><span class="kw ns">::</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/everything.html">everything</a></span>()) <span class="co"># moves Model to first col</span></pre></body></html></div>
<p>Look at the model table</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="no">df.mods</span>
<span class="co">#&gt;   Model Recruitment ecov_process ecov_how</span>
<span class="co">#&gt; 1    m1           2           rw        0</span>
<span class="co">#&gt; 2    m2           2           rw        1</span>
<span class="co">#&gt; 3    m3           3           rw        0</span>
<span class="co">#&gt; 4    m4           3           rw        2</span>
<span class="co">#&gt; 5    m5           3          ar1        2</span>
<span class="co">#&gt; 6    m6           3          ar1        1</span>
<span class="co">#&gt; 7    m7           4          ar1        1</span></pre></body></html></div>
<p>We specify the options for modeling recruitment and any environmental covariate(s) using the <code><a href="../reference/prepare_wham_input.html">prepare_wham_input()</a></code> function. WHAM provides 4 options for recruitment (<code>recruit_model</code>):</p>
<ol style="list-style-type: decimal">
<li>random walk,</li>
<li>random about mean,</li>
<li>Beverton-Holt, and</li>
<li>Ricker.</li>
</ol>
<p>The environmental covariate options are fed to <code><a href="../reference/prepare_wham_input.html">prepare_wham_input()</a></code> as a list, <code>ecov</code>:</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r">  <span class="no">m</span><span class="kw">=</span><span class="fl">1</span> <span class="co"># example for first model</span>
  <span class="no">ecov</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
    <span class="kw">label</span> <span class="kw">=</span> <span class="st">"CPI"</span>,
    <span class="kw">mean</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="no">env.dat</span>$<span class="no">CPI</span>),
    <span class="kw">logsigma</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">env.dat</span>$<span class="no">CPI_sigma</span>)),
    <span class="kw">year</span> <span class="kw">=</span> <span class="no">env.dat</span>$<span class="no">Year</span>,
    <span class="kw">use_obs</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span>(<span class="fl">1</span>, <span class="kw">ncol</span><span class="kw">=</span><span class="fl">1</span>, <span class="kw">nrow</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(<span class="no">env.dat</span>)[<span class="fl">1</span>]), <span class="co"># use all obs (all = 1)</span>
    <span class="kw">lag</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="co"># CPI in year t affects recruitment in year t+1</span>
    <span class="kw">process_model</span> <span class="kw">=</span> <span class="no">df.mods</span>$<span class="no">ecov_process</span>[<span class="no">m</span>], <span class="co"># "rw" or "ar1"</span>
    <span class="kw">where</span> <span class="kw">=</span> <span class="st">"recruit"</span>, <span class="co"># CPI affects recruitment</span>
    <span class="kw">how</span> <span class="kw">=</span> <span class="no">df.mods</span>$<span class="no">ecov_how</span>[<span class="no">m</span>]) <span class="co"># 0 = no effect, 1 = controlling, 2 = limiting</span></pre></body></html></div>
<p>There are currently 2 options for the <code>ecov</code> process model (<code>ecov$process_model</code>): 1) random walk (<code>'rw'</code>), and 2) autoregressive (<code>'ar1'</code>). We must next specify <strong>where</strong> the <code>ecov</code> affects the population; here it is via recruitment (<code>ecov$where = "recruit"</code>) as opposed to another process like catchability, mortality, maturity, etc. The options for <strong>how</strong> the <code>ecov</code> affects recruitment (<code>ecov$how</code>) follow <a href="https://www.sciencedirect.com/science/article/pii/S1385110197000221">Iles and Beverton (1998)</a> and <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/fog.12236">Xu et al. (2018)</a>:</p>
<ol style="list-style-type: decimal">
<li>“controlling” (dens-indep mortality),</li>
<li>“limiting” (carrying capacity, e.g. <code>ecov</code> determines amount of suitable habitat),</li>
<li>“lethal” (threshold, i.e. R –&gt; 0 at some <code>ecov</code> value),<br>
</li>
<li>“masking” (metabolic/growth, <code>ecov</code> decreases dR/dS), and</li>
<li>“directive” (e.g. behavioral).</li>
</ol>
<p>Finally, we specify the <strong>lag</strong> at which CPI affects recruitment (<code>ecov$lag = 1</code>, i.e. CPI in year <em>t</em> affects recruitment in year <em>t + 1</em>).</p>
<p>You can set <code>ecov = NULL</code> to fit the model without environmental covariate data, but note that here we fit the <code>ecov</code> data even for models without an <code>ecov</code> effect on recruitment (<code>m1</code> and <code>m3</code>) so that we can compare them via AIC (need to have the same data in the likelihood). We accomplish this by setting <code>ecov$how = 0</code>.</p>
<p>Options are described in the <code><a href="../reference/prepare_wham_input.html">prepare_wham_input()</a></code> help page. Not all <code>ecov$how</code> options are implemented for every recruitment model.</p>
<div class="sourceCode" id="cb13"><html><body><pre class="r">?<span class="no">prepare_wham_input</span></pre></body></html></div>
</div>
<div id="run-the-models" class="section level2">
<h2 class="hasAnchor">
<a href="#run-the-models" class="anchor"></a>3. Run the models</h2>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="kw">for</span>(<span class="no">m</span> <span class="kw">in</span> <span class="fl">1</span>:<span class="no">n.mods</span>){
  <span class="co"># set up environmental covariate data and model options</span>
  <span class="no">ecov</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
    <span class="kw">label</span> <span class="kw">=</span> <span class="st">"CPI"</span>,
    <span class="kw">mean</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="no">env.dat</span>$<span class="no">CPI</span>),
    <span class="kw">logsigma</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">env.dat</span>$<span class="no">CPI_sigma</span>)),
    <span class="kw">year</span> <span class="kw">=</span> <span class="no">env.dat</span>$<span class="no">Year</span>,
    <span class="kw">use_obs</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span>(<span class="fl">1</span>, <span class="kw">ncol</span><span class="kw">=</span><span class="fl">1</span>, <span class="kw">nrow</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(<span class="no">env.dat</span>)[<span class="fl">1</span>]), <span class="co"># use all obs (=1)</span>
    <span class="kw">lag</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="co"># CPI in year t affects recruitment in year t+1</span>
    <span class="kw">process_model</span> <span class="kw">=</span> <span class="no">df.mods</span>$<span class="no">Ecov_process</span>[<span class="no">m</span>], <span class="co"># "rw" or "ar1"</span>
    <span class="kw">where</span> <span class="kw">=</span> <span class="st">"recruit"</span>, <span class="co"># CPI affects recruitment</span>
    <span class="kw">how</span> <span class="kw">=</span> <span class="no">df.mods</span>$<span class="no">Ecov_how</span>[<span class="no">m</span>]) <span class="co"># 0 = no effect (but still fit Ecov to compare AIC)</span>

  <span class="co"># (not used in this vignette) can set ecov = NULL to fit model without ecov data</span>
  <span class="kw">if</span>(<span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(<span class="no">df.mods</span>$<span class="no">ecov_process</span>[<span class="no">m</span>])) <span class="no">ecov</span> <span class="kw">=</span> <span class="kw">NULL</span>

  <span class="co"># generate wham input from ASAP3 and ecov data</span>
  <span class="no">input</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/prepare_wham_input.html">prepare_wham_input</a></span>(<span class="no">asap3</span>, <span class="kw">recruit_model</span> <span class="kw">=</span> <span class="no">df.mods</span>$<span class="no">Recruitment</span>[<span class="no">m</span>],
                              <span class="kw">model_name</span> <span class="kw">=</span> <span class="st">"Ex 2: SNEMA Yellowtail Flounder with CPI effects on R"</span>,
                              <span class="kw">ecov</span> <span class="kw">=</span> <span class="no">ecov</span>,
                              <span class="kw">NAA_re</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">sigma</span><span class="kw">=</span><span class="st">"rec+1"</span>, <span class="kw">cor</span><span class="kw">=</span><span class="st">"iid"</span>))

  <span class="co"># Builds off model m4 in example 1:</span>
  <span class="co">#   full state-space model: NAA_re = list(sigma="rec+1", cor="iid")</span>
  <span class="co">#   logistic normal age-compositions (below)</span>

  <span class="co"># Age comp model = logistic normal pool obs (not multinomial, the default)</span>
  <span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_fleets</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="fl">5</span>, <span class="no">input</span>$<span class="no">data</span>$<span class="no">n_fleets</span>) <span class="co"># 5 = logistic normal (pool zero obs)</span>
  <span class="no">input</span>$<span class="no">data</span>$<span class="no">n_age_comp_pars_fleets</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">3</span>,<span class="fl">1</span>,<span class="fl">2</span>)[<span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_fleets</span>]
  <span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_indices</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="fl">5</span>, <span class="no">input</span>$<span class="no">data</span>$<span class="no">n_indices</span>) <span class="co"># 5 = logistic normal (pool zero obs)</span>
  <span class="no">input</span>$<span class="no">data</span>$<span class="no">n_age_comp_pars_indices</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">3</span>,<span class="fl">1</span>,<span class="fl">2</span>)[<span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_indices</span>]
  <span class="no">n_catch_acomp_pars</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">3</span>,<span class="fl">1</span>,<span class="fl">2</span>)[<span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_fleets</span>[<span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="no">input</span>$<span class="no">data</span>$<span class="no">use_catch_paa</span>,<span class="fl">2</span>,<span class="no">sum</span>)<span class="kw">&gt;</span><span class="fl">0</span>)]]
  <span class="no">n_index_acomp_pars</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">3</span>,<span class="fl">1</span>,<span class="fl">2</span>)[<span class="no">input</span>$<span class="no">data</span>$<span class="no">age_comp_model_indices</span>[<span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="no">input</span>$<span class="no">data</span>$<span class="no">use_index_paa</span>,<span class="fl">2</span>,<span class="no">sum</span>)<span class="kw">&gt;</span><span class="fl">0</span>)]]
  <span class="no">input</span>$<span class="no">par</span>$<span class="no">catch_paa_pars</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">n_catch_acomp_pars</span>))
  <span class="no">input</span>$<span class="no">par</span>$<span class="no">index_paa_pars</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">n_index_acomp_pars</span>))

  <span class="co"># Selectivity = logistic, not age-specific as in ex1</span>
  <span class="co">#   2 pars per block instead of n.ages</span>
  <span class="co">#   sel pars of indices 4/5 fixed at 1.5, 0.1 (specified via neg phase in ex2_SNEMAYT.dat)</span>
  <span class="no">input</span>$<span class="no">par</span>$<span class="no">logit_selpars</span>[<span class="fl">1</span>:<span class="fl">4</span>,<span class="fl">7</span>:<span class="fl">8</span>] <span class="kw">&lt;-</span> <span class="fl">0</span> <span class="co"># last 2 rows will not be estimated (mapped to NA)</span>

  <span class="co"># Fit model</span>
  <span class="no">mod</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fit_wham.html">fit_wham</a></span>(<span class="no">input</span>, <span class="kw">do.retro</span><span class="kw">=</span><span class="fl">TRUE</span>, <span class="kw">do.osa</span><span class="kw">=</span><span class="fl">TRUE</span>)

  <span class="co"># Save model</span>
  <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">saveRDS</a></span>(<span class="no">mod</span>, <span class="kw">file</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="no">df.mods</span>$<span class="no">Model</span>[<span class="no">m</span>],<span class="st">".rds"</span>))

  <span class="co"># Plot output in new subfolder</span>
  <span class="fu"><a href="../reference/plot_wham_output.html">plot_wham_output</a></span>(<span class="kw">mod</span><span class="kw">=</span><span class="no">mod</span>, <span class="kw">dir.main</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/getwd.html">getwd</a></span>(),<span class="no">df.mods</span>$<span class="no">Model</span>[<span class="no">m</span>]), <span class="kw">out.type</span><span class="kw">=</span><span class="st">'html'</span>)
}</pre></body></html></div>
</div>
<div id="check-for-convergence" class="section level2">
<h2 class="hasAnchor">
<a href="#check-for-convergence" class="anchor"></a>4. Check for convergence</h2>
<p>Collect all models into a list.</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="no">mod.list</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="no">df.mods</span>$<span class="no">Model</span>,<span class="st">".rds"</span>)
<span class="no">mods</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span>(<span class="no">mod.list</span>, <span class="no">readRDS</span>)</pre></body></html></div>
<p>There is no indication that any of the models failed to converge. In addition, SE estimates are calculable for all models (invertible Hessian, <code><a href="https://rdrr.io/pkg/TMB/man/sdreport.html">TMB::sdreport()</a></code> succeeds).</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="no">vign2_conv</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span>(<span class="no">mods</span>, <span class="kw">function</span>(<span class="no">x</span>) <span class="fu"><a href="https://rdrr.io/r/utils/capture.output.html">capture.output</a></span>(<span class="fu"><a href="../reference/check_convergence.html">check_convergence</a></span>(<span class="no">x</span>)))
<span class="kw">for</span>(<span class="no">m</span> <span class="kw">in</span> <span class="fl">1</span>:<span class="no">n.mods</span>) <span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="st">"Model "</span>,<span class="no">m</span>,<span class="st">":"</span>), <span class="no">vign2_conv</span><span class="kw">[[</span><span class="no">m</span>]], <span class="st">""</span>, <span class="kw">sep</span><span class="kw">=</span><span class="st">'\n'</span>)</pre></body></html></div>
<pre><code>#&gt; Model 1:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 1.16e-09 
#&gt; Max gradient parameter: logit_selpars 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 2:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 1.10e-09 
#&gt; Max gradient parameter: F_devs 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 3:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 4.92e-10 
#&gt; Max gradient parameter: logit_selpars 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 4:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 8.37e-10 
#&gt; Max gradient parameter: logit_selpars 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 5:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 9.77e-11 
#&gt; Max gradient parameter: F_devs 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 6:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 1.20e-09 
#&gt; Max gradient parameter: logit_selpars 
#&gt; TMB:sdreport() was performed successfully for this model
#&gt; 
#&gt; Model 7:
#&gt; stats:nlminb thinks the model has converged: mod$opt$convergence == 0
#&gt; Maximum gradient component: 1.66e-09 
#&gt; Max gradient parameter: F_devs 
#&gt; TMB:sdreport() was performed successfully for this model</code></pre>
</div>
<div id="compare-models" class="section level2">
<h2 class="hasAnchor">
<a href="#compare-models" class="anchor"></a>5. Compare models</h2>
<p>Calculate AIC and Mohn’s rho using <code><a href="../reference/compare_wham_models.html">compare_wham_models()</a></code>.</p>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="no">df.aic</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/compare_wham_models.html">compare_wham_models</a></span>(<span class="no">mods</span>, <span class="kw">sort</span><span class="kw">=</span><span class="fl">FALSE</span>)$<span class="no">tab</span> <span class="co"># can't sort yet bc going to make labels prettier</span>
<span class="no">df.mods</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span>(<span class="no">df.mods</span>, <span class="no">df.aic</span>)</pre></body></html></div>
<p>Print and save the results table. <code>m6</code> has the lowest AIC (Bev-Holt recruitment, CPI modeled as AR1, controlling effect of CPI on recruitment).</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="co"># make results table prettier</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span>(<span class="no">df.mods</span>) <span class="kw">&lt;-</span> <span class="kw">NULL</span>
<span class="no">df.mods</span>$<span class="no">Recruitment</span> <span class="kw">&lt;-</span> <span class="kw pkg">dplyr</span><span class="kw ns">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span>(<span class="no">df.mods</span>$<span class="no">Recruitment</span>, <span class="kw">`2`</span><span class="kw">=</span><span class="st">'Random'</span>, <span class="kw">`3`</span><span class="kw">=</span><span class="st">'Bev-Holt'</span>, <span class="kw">`4`</span><span class="kw">=</span><span class="st">'Ricker'</span>)
<span class="no">df.mods</span>$<span class="no">ecov_how</span> <span class="kw">&lt;-</span> <span class="kw pkg">dplyr</span><span class="kw ns">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span>(<span class="no">df.mods</span>$<span class="no">ecov_how</span>, <span class="kw">`0`</span><span class="kw">=</span><span class="st">'---'</span>,<span class="kw">`1`</span><span class="kw">=</span><span class="st">'Controlling'</span>, <span class="kw">`2`</span><span class="kw">=</span><span class="st">'Limiting'</span>, <span class="kw">`4`</span><span class="kw">=</span><span class="st">'Masking'</span>)
<span class="no">df.mods</span>$<span class="no">NLL</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(<span class="no">mods</span>, <span class="kw">function</span>(<span class="no">x</span>) <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="no">x</span>$<span class="no">opt</span>$<span class="no">objective</span>,<span class="fl">3</span>))
<span class="no">df.mods</span> <span class="kw">&lt;-</span> <span class="no">df.mods</span>[<span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span>(<span class="no">df.mods</span>$<span class="no">dAIC</span>),]
<span class="fu"><a href="https://rdrr.io/r/base/save.html">save</a></span>(<span class="st">"df.mods"</span>, <span class="kw">file</span><span class="kw">=</span><span class="st">"vign2_res.RData"</span>)

<span class="no">df.mods</span></pre></body></html></div>
<pre><code>#&gt;    Model Recruitment Ecov_process    Ecov_how      NLL dAIC     AIC  rho_R
#&gt; m6    m6    Bev-Holt          ar1 Controlling -829.662  0.0 -1519.3 0.1909
#&gt; m5    m5    Bev-Holt          ar1    Limiting -829.235  0.8 -1518.5 0.1970
#&gt; m7    m7      Ricker          ar1 Controlling -829.061  1.2 -1518.1 0.1899
#&gt; m4    m4    Bev-Holt           rw    Limiting -818.535 20.2 -1499.1 0.1965
#&gt; m2    m2      Random           rw Controlling -815.937 23.4 -1495.9 0.2046
#&gt; m3    m3    Bev-Holt           rw         --- -812.993 29.3 -1490.0 0.2133
#&gt; m1    m1      Random           rw         --- -808.943 35.4 -1483.9 0.2308
#&gt;    rho_SSB rho_Fbar runtime
#&gt; m6  0.0633  -0.1023     0.3
#&gt; m5  0.0665  -0.1055     0.3
#&gt; m7  0.0607  -0.0998     0.4
#&gt; m4  0.0668  -0.1057     0.3
#&gt; m2  0.0696  -0.1108     0.2
#&gt; m3  0.0659  -0.1039     0.3
#&gt; m1  0.0682  -0.1106     0.2</code></pre>
</div>
<div id="results" class="section level2">
<h2 class="hasAnchor">
<a href="#results" class="anchor"></a>6. Results</h2>
<p>There are 3 options for plotting WHAM output. The default (<code>out.type='html'</code>) creates and opens an HTML file with plots organized into tabs (code modified from <a href="https://github.com/r4ss/r4ss/blob/master/R/SS_html.R"><code>r4ss::SS_html()</code></a>):</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="co"># save output plots in subfolder for each model</span>
<span class="kw">for</span>(<span class="no">m</span> <span class="kw">in</span> <span class="fl">1</span>:<span class="no">n.mods</span>) <span class="fu"><a href="../reference/plot_wham_output.html">plot_wham_output</a></span>(<span class="kw">mod</span><span class="kw">=</span><span class="no">mods</span><span class="kw">[[</span><span class="no">m</span>]], <span class="kw">dir.main</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/getwd.html">getwd</a></span>(), <span class="no">df.mods</span>$<span class="no">Model</span>[<span class="no">m</span>]), <span class="kw">out.type</span><span class="kw">=</span><span class="st">'html'</span>)</pre></body></html></div>
<div id="cold-pool-index-cpi" class="section level3">
<h3 class="hasAnchor">
<a href="#cold-pool-index-cpi" class="anchor"></a>Cold Pool Index (CPI)</h3>
<p>Models that included an effect of the Cold Pool Index on recruitment were strongly supported by AIC over models without CPI effects (<code>m2</code> and <code>m4-7</code> lower AIC than <code>m1</code> and <code>m3</code>). Note that we can compare models with and without a CPI effect on recruitment using AIC because we also fit the CPI data in the models without the effect (<code>m1</code> and <code>m3</code>).</p>
<p>Comparing <code>m4</code> and <code>m5</code> demonstrates that the CPI was best modeled as an AR1 process (<code>m5</code>) instead of a random walk (<code>m4</code>), since this was the only difference between the two models and <code>m5</code> had lower AIC. In addition, the one-step-ahead residuals for the CPI from <code>m5</code> (right) are smaller and conform more closely to a normal distribution than in <code>m4</code> (left):</p>
<p><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/OSAresid_ecov_m4.png" alt="OSA residuals for the CPI, model 4." style="width:45.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/OSAresid_ecov_m5.png" alt="OSA residuals for the CPI, model 5." style="width:45.0%"></p>
<p>Compared to the base model (<code>m1</code>, left), the best model that included CPI and SSB effects on recruitment, (<code>m6</code>, right) reduced the retrospective pattern in recruitment, <span class="math inline">\(\rho_R\)</span>, very slightly from 0.231 to 0.191.</p>
<p><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/NAA_age1_retro_relative_m1.png" alt="Retrospective pattern in recruitment, m1." style="width:45.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/NAA_age1_retro_relative_m6.png" alt="Retrospective pattern in recruitment, m6." style="width:45.0%"></p>
</div>
<div id="recruitment" class="section level3">
<h3 class="hasAnchor">
<a href="#recruitment" class="anchor"></a>Recruitment</h3>
<p>Beverton-Holt recruitment was preferred over random (<code>m4</code> lower AIC than <code>m2</code>) and weakly preferred over Ricker (<code>m6</code> lower AIC than <code>m7</code>). Models that included both Bev-Holt and CPI effects on recruitment had lower AIC than the model with Bev-Holt but without the CPI (<code>m4</code> vs. <code>m3</code>). Adding the CPI effect to the Bev-Holt explains some of the variability around the stock-recruit curve, which resulted in <code>m4</code> (right) estimating lower <span class="math inline">\(\sigma^2_R\)</span> than <code>m3</code> (left).</p>
<p><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/SSB_Rec_m3.png" alt="Bev-Holt fit from m3, without a CPI effect." style="width:45.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/SSB_Rec_m4.png" alt="Bev-Holt fit from m4, WITH a CPI effect." style="width:45.0%"></p>
<p>There was very weak evidence that the Cold Pool <em>controls</em> recruitment, as opposed to <em>limiting</em> recruitment (<code>m5</code> vs. <code>m6</code>). The hypothesis that the CPI indicates the amount of suitable habitat for juvenile yellowtail flounder corresponds to a limiting effect, as in <code>m5</code>. In contrast, a controlling effect (as in <code>m6</code>) causes density-independent mortality. For more explanation, see <a href="https://www.sciencedirect.com/science/article/pii/S1385110197000221">Iles &amp; Beverton (1998)</a>.</p>
</div>
<div id="stock-status" class="section level3">
<h3 class="hasAnchor">
<a href="#stock-status" class="anchor"></a>Stock status</h3>
<p>Whether or not to include a stock-recruit function and/or the CPI did not have a great influence on estimated stock status. Specifically, the models hardly differed in their estimation of the probability that the stock was overfished, <span class="math inline">\(Pr[SSB &lt; 0.5 \: SSB_{40\%}]\)</span>. All models estimated with 100% probability that the stock was not experiencing overfishing in 2011, <span class="math inline">\(F &lt; F_{40\%}\)</span>.</p>
<p><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/Kobe_status_m1.png" alt="Stock status, m1." style="width:45.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/Kobe_status_m3.png" alt="Stock status, m3." style="width:45.0%"></p>
<p><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/Kobe_status_m2.png" alt="Stock status, m2." style="width:30.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/Kobe_status_m4.png" alt="Stock status, m4." style="width:30.0%"><img src="https://raw.githubusercontent.com/timjmiller/wham/master/vignettes/ex2_plots/Kobe_status_m6.png" alt="Stock status, m6." style="width:30.0%"></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Tim Miller, Brian Stock.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
